version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "10:00"
    timezone: Etc/UCT
  reviewers:
  - RandomByte
  - svbender
  versioning-strategy: increase
  ignore:
  - dependency-name: semver
    versions:
    - "< 5.5.2"
    - ">= 5.5.1.a"
