language: node_js # don't install any environment

node_js:
- "node"

os:
- linux
- osx
- windows

matrix:
  include:
    - os: linux
      node_js:
        - "10"
    - os: linux
      node_js:
        - "8"

after_script:
- if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then npm run report-coveralls; fi

notifications:
  webhooks: https://coveralls.io/webhook
