language: node_js # don't install any environment

node_js:
- "lts/*"

script: npm run coverage

after_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" &&
    (( -n "$TRAVIS_PULL_REQUEST" && "$TRAVIS_PULL_REQUEST" != "false" ) || "$TRAVIS_BRANCH" == "master" ) ]]; then
    npm run report-coveralls;
  fi

notifications:
  webhooks: https://coveralls.io/webhook
