language: node_js # don't install any environment

node_js:
- "11"

os:
- linux
- osx
- windows

matrix:
  include:
    - os: linux
      node_js:
        - "10"
    - os: linux
      node_js:
        - "8"

after_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" &&
    (( -n "$TRAVIS_PULL_REQUEST" && "$TRAVIS_PULL_REQUEST" != "false" ) || "$TRAVIS_BRANCH" == "master" ) ]]; then
    npm run report-coveralls;
  fi

notifications:
  webhooks: https://coveralls.io/webhook
