blank_issues_enabled: false
contact_links:
  - name: Report UI5 Tooling Issues or Request a Feature
    url: https://github.com/SAP/ui5-tooling/issues/new/choose
    about: Please create new issues in the UI5 Tooling repository
