style: github
template: RELEASE.tpl.md
info:
  repository_url: https://github.com/SAP/ui5-cli
options:
  commits:
    filters:
      Type:
        - FEATURE
        - FIX
        - PERF
        - DEPENDENCY
  commit_groups:
    title_maps:
       FEATURE: Features
       FIX: Bug Fixes
       PERF: Performance Improvements
       DEPENDENCY: Dependency Updates
  header:
    pattern: "^\\[(\\w*)\\]\\s(?:([^\\:]*)\\:\\s)?(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  issues:
    prefix:
      - "#"
  notes:
    keywords:
      - BREAKING CHANGE
