style: github
template: RELEASE.tpl.md
info:
  repository_url: https://github.com/SAP/ui5-cli
options:
  tag_filter_pattern: '^v[^0123]' # For release notes ignore versions below v4 to that we always compare the _last v4+_ tag with the current release
  commits:
    filters:
      Type:
        - FEATURE
        - FIX
        - PERF
        - DEPENDENCY
        - BREAKING
  commit_groups:
    title_maps:
       FEATURE: Features
       FIX: Bug Fixes
       PERF: Performance Improvements
       DEPENDENCY: Dependency Updates
       BREAKING: Breaking Changes
  header:
    pattern: "^\\[(\\w*)\\]\\s(?:([^\\:]*)\\:\\s)?(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  issues:
    prefix:
      - "#"
  notes:
    keywords:
      - BREAKING CHANGE
