name: GitHub CI

on:
  push:
    branches:
      - v4
  pull_request:
    branches:
      - v4

# No permissions are required for this workflow
permissions: {}

jobs:
  test:
    name: General checks, tests and coverage reporting
    runs-on: ubuntu-24.04
    steps:

    - uses: actions/checkout@v7

    - name: Use Node.js LTS 22
      uses: actions/setup-node@v6.4.0
      with:
        node-version: 22

    - name: Install dependencies
      run: npm ci

    - name: Check Node.js engine compatibility
      run: npm run check-engine

    - name: Perform dependencies analysis
      run: npm run knip

    - name: Perform checks and tests
      run: npm test

    - name: Send report to Coveralls
      uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329 # v2.3.8

    - name: Build e2e test image
      run: ./test/e2e/build-image.sh

    - name: Run e2e test image
      run: ./test/e2e/run-image.sh
