name: Tests

on:
  push:
    branches:
      - v4
  pull_request:
    branches:
      - v4

# No permissions are required for this workflow
permissions: {}

jobs:
  test:
    name: Unit and Integration
    strategy:
      fail-fast: false # Do not stop other jobs if one fails
      matrix:
        version: ["20.11.0", 22, 24, 25, 26]
        os: [ubuntu-24.04, windows-2025, macos-15]
    runs-on: ${{ matrix.os }}
    steps:

    - uses: actions/checkout@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.version }}

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: npm run unit
